import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from './api.js';
import { useAuth } from './auth.jsx';
import { Status } from './components.jsx';

export function LoginPage() {
  const { login, user } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState('');
  if (user) return navigate(user.role === 'admin' ? '/admin/videos' : '/learn');
  async function submit(event) { event.preventDefault(); setError(''); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const { data: session } = await api.post('/auth/login', data); login(session); navigate(session.user.role === 'admin' ? '/admin/videos' : '/learn'); } catch (e) { setError(e.response?.data?.message || 'Unable to sign in'); } }
  return <main className="auth"><form className="card" onSubmit={submit}><h1>Welcome back</h1><p>Sign in to manage or learn from video courses.</p><label>Email<input type="email" name="email" required defaultValue="admin@example.com" /></label><label>Password<input type="password" name="password" required defaultValue="Password123!" /></label>{error && <p className="error">{error}</p>}<button>Sign in</button><small>Seed accounts: admin@example.com or learner@example.com</small></form></main>;
}

export function AdminVideosPage() {
  const client = useQueryClient(); const [editing, setEditing] = useState(null);
  const query = useQuery({ queryKey: ['admin-videos'], queryFn: () => api.get('/videos').then((r) => r.data.videos) });
  const save = useMutation({ mutationFn: ({ id, payload }) => id ? api.patch(`/videos/${id}`, payload) : api.post('/videos', payload), onSuccess: () => { client.invalidateQueries({ queryKey: ['admin-videos'] }); setEditing(null); } });
  const publish = useMutation({ mutationFn: ({ id, isPublished }) => api.patch(`/videos/${id}/publish`, { isPublished }), onSuccess: () => client.invalidateQueries({ queryKey: ['admin-videos'] }) });
  function submit(event) { event.preventDefault(); const raw = Object.fromEntries(new FormData(event.currentTarget)); save.mutate({ id: editing?._id, payload: { ...raw, durationSeconds: Number(raw.durationSeconds) } }); }
  return <main><div className="page-title"><div><h1>Videos</h1><p>Create, publish, and maintain learning content.</p></div><button onClick={() => setEditing({})}>New video</button></div>{editing && <form className="card form-grid" onSubmit={submit}><h2>{editing._id ? 'Edit video' : 'New video'}</h2><label>Title<input name="title" required defaultValue={editing.title} /></label><label>Video URL<input name="videoUrl" type="url" required defaultValue={editing.videoUrl} /></label><label>Duration (seconds)<input name="durationSeconds" type="number" min="1" required defaultValue={editing.durationSeconds} /></label><label>Thumbnail URL<input name="thumbnailUrl" type="url" defaultValue={editing.thumbnailUrl} /></label><label className="wide">Description<textarea name="description" defaultValue={editing.description} /></label><div><button disabled={save.isPending}>Save video</button><button type="button" className="secondary" onClick={() => setEditing(null)}>Cancel</button></div></form>}<Status loading={query.isLoading} error={query.error} empty={!query.data?.length && 'No videos yet.'}>{query.data?.map((video) => <article className="card row" key={video._id}><div><h2>{video.title}</h2><p>{video.description || 'No description'}</p><span className={video.isPublished ? 'pill live' : 'pill'}>{video.isPublished ? 'Published' : 'Draft'}</span></div><div className="actions"><Link className="button secondary" to={`/admin/videos/${video._id}/questions`}>Questions</Link><button className="secondary" onClick={() => setEditing(video)}>Edit</button><button onClick={() => publish.mutate({ id: video._id, isPublished: !video.isPublished })}>{video.isPublished ? 'Unpublish' : 'Publish'}</button></div></article>)}</Status></main>;
}

export function QuestionsPage() {
  const { videoId } = useParams(); const client = useQueryClient(); const [kind, setKind] = useState('single');
  const query = useQuery({ queryKey: ['questions', videoId], queryFn: () => api.get(`/videos/${videoId}/questions`).then((r) => r.data.questions) });
  const create = useMutation({ mutationFn: (payload) => api.post(`/videos/${videoId}/questions`, payload), onSuccess: () => { client.invalidateQueries({ queryKey: ['questions', videoId] }); } });
  function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); const options = String(form.get('options') || '').split('\n').map((text) => text.trim()).filter(Boolean).map((text) => ({ text })); create.mutate({ timestampSeconds: Number(form.get('timestampSeconds')), type: kind, prompt: form.get('prompt'), options, correctOptionIds: [], acceptedAnswers: [] }, { onSuccess: () => event.currentTarget.reset() }); }
  return <main><Link to="/admin/videos">← Back to videos</Link><h1>Timestamp questions</h1><form className="card form-grid" onSubmit={submit}><label>Timestamp (seconds)<input name="timestampSeconds" type="number" min="0" required /></label><label>Type<select value={kind} onChange={(e) => setKind(e.target.value)}><option value="single">Single choice</option><option value="multiple">Multiple choice</option><option value="short">Short answer</option></select></label><label className="wide">Question<textarea name="prompt" required /></label>{kind !== 'short' && <label className="wide">Options (one per line)<textarea name="options" required /></label>}<div><button disabled={create.isPending}>Add question</button></div>{create.error && <p className="error">{create.error.response?.data?.message || 'Unable to add question'}</p>}</form><Status loading={query.isLoading} error={query.error} empty={!query.data?.length && 'No questions yet.'}>{query.data?.map((question) => <article className="card" key={question._id}><strong>{question.timestampSeconds}s · {question.type}</strong><p>{question.prompt}</p></article>)}</Status></main>;
}

export function AdminAssignmentsPage() {
  const client = useQueryClient(); const [message, setMessage] = useState('');
  const videos = useQuery({ queryKey: ['admin-videos'], queryFn: () => api.get('/videos').then((r) => r.data.videos) });
  const learners = useQuery({ queryKey: ['learners'], queryFn: () => api.get('/users/learners').then((r) => r.data.learners) });
  const assignments = useQuery({ queryKey: ['admin-assignments'], queryFn: () => api.get('/assignments').then((r) => r.data.assignments) });
  const refresh = () => client.invalidateQueries({ queryKey: ['admin-assignments'] });
  const create = useMutation({ mutationFn: (payload) => api.post('/assignments', payload), onError: (error) => setMessage(error.response?.data?.message || 'Unable to create assignment.') });
  const remove = useMutation({ mutationFn: (id) => api.delete(`/assignments/${id}`), onSuccess: refresh });
  function submit(event) { event.preventDefault(); setMessage(''); create.mutate(Object.fromEntries(new FormData(event.currentTarget)), { onSuccess: () => { event.currentTarget.reset(); setMessage('Video assigned successfully.'); refresh(); } }); }
  const loading = videos.isLoading || learners.isLoading || assignments.isLoading;
  const error = videos.error || learners.error || assignments.error;
  const publishedVideos = videos.data?.filter((video) => video.isPublished) || [];
  return <main><div className="page-title"><div><h1>Assignments</h1><p>Give learners access to published video lessons and manage existing assignments.</p></div></div><form className="card form-grid" onSubmit={submit}><h2 className="wide">Assign a video</h2><label>Published video<select name="videoId" required defaultValue=""><option value="" disabled>Select a published video</option>{publishedVideos.map((video) => <option key={video._id} value={video._id}>{video.title}</option>)}</select></label><label>Learner<select name="learnerId" required defaultValue=""><option value="" disabled>Select a learner</option>{learners.data?.map((learner) => <option key={learner._id} value={learner._id}>{learner.name} - {learner.email}</option>)}</select></label><div><button disabled={create.isPending || !publishedVideos.length || !learners.data?.length}>Assign video</button></div>{!videos.isLoading && !publishedVideos.length && <p className="hint wide">Publish a video first; draft videos cannot be assigned.</p>}{message && <p className={message.includes('successfully') ? 'success' : 'error'}>{message}</p>}</form><Status loading={loading} error={error} empty={!assignments.data?.length && 'No learner assignments yet.'}>{assignments.data?.map((assignment) => <article className="card row" key={assignment._id}><div><h2>{assignment.videoId?.title || 'Deleted video'}</h2><p>Assigned to {assignment.learnerId?.name || 'Deleted user'} ({assignment.learnerId?.email})</p><span className="pill">Published video</span></div><button className="secondary" disabled={remove.isPending} onClick={() => remove.mutate(assignment._id)}>Remove</button></article>)}</Status></main>;
}

export function LearnerHomePage() {
  const query = useQuery({ queryKey: ['assignments'], queryFn: () => api.get('/assignments/me').then((r) => r.data.assignments) });
  return <main><div className="page-title"><div><h1>My learning</h1><p>Your assigned and published video lessons.</p></div></div><Status loading={query.isLoading} error={query.error} empty={!query.data?.length && 'No published videos are assigned to you yet. Ask your admin to publish and assign a lesson.'}>{query.data?.map(({ assignment, video, progress }) => { const percent = Math.round(progress?.completionPercentage || 0); const completed = progress?.status === 'completed' || percent >= 100; return <article className="card row" key={assignment._id}><div className="lesson-info"><h2>{video.title}</h2><p>{video.description || 'No description provided.'}</p><div className="progress-label"><span>{completed ? 'Completed' : progress?.status === 'in_progress' ? 'In progress' : 'Not started'}</span><strong>{percent}%</strong></div><div className="progress-track" aria-label={`${percent}% complete`}><span style={{ width: `${percent}%` }} /></div></div><Link className={completed ? 'button secondary' : 'button'} to={`/learn/${assignment._id}`}>{completed ? 'Review video' : progress ? 'Continue learning' : 'Start learning'}</Link></article>; })}</Status></main>;
}

export function PlayerPage() {
  const { assignmentId } = useParams(); const player = useRef(null); const client = useQueryClient(); const lastSavedSecond = useRef(0); const [activeQuestion, setActiveQuestion] = useState(null); const [answer, setAnswer] = useState(''); const [handledQuestionIds, setHandledQuestionIds] = useState([]); const [notice, setNotice] = useState(''); const [playerError, setPlayerError] = useState('');
  const query = useQuery({ queryKey: ['play', assignmentId], queryFn: () => api.get(`/assignments/${assignmentId}/play`).then((r) => r.data) });
  const saveProgress = useMutation({ mutationFn: (payload) => api.patch(`/assignments/${assignmentId}/progress`, payload), onSuccess: () => client.invalidateQueries({ queryKey: ['assignments'] }) });
  const saveResponse = useMutation({ mutationFn: (payload) => api.post(`/assignments/${assignmentId}/responses`, payload), onSuccess: (_, variables) => { setHandledQuestionIds((current) => [...new Set([...current, variables.questionId])]); setActiveQuestion(null); setAnswer(''); setNotice('Answer saved. Playback resumed.'); player.current?.play().catch(() => setPlayerError('Select play to continue the video.')); } });
  useEffect(() => { if (query.data?.progress?.lastWatchedSecond && player.current) player.current.currentTime = query.data.progress.lastWatchedSecond; }, [query.data?.progress?.lastWatchedSecond]);
  useEffect(() => { setHandledQuestionIds((query.data?.progress?.answeredQuestionIds || []).map(String)); }, [query.data?.progress?.answeredQuestionIds]);
  if (query.isLoading || query.error) return <main><Status loading={query.isLoading} error={query.error} /></main>;
  return <PlayerExperience assignmentId={assignmentId} data={query.data} />;
  /* Retained temporarily only to preserve the prior implementation while this player flow is refactored.
  const { video, questions, progress } = query.data; const answered = new Set(handledQuestionIds); const isCompleted = progress?.status === 'completed';
  function persistProgress(currentTime, completed = false) { const duration = player.current?.duration || video.durationSeconds; const percentage = completed ? 100 : Math.min(99, Math.round((currentTime / duration) * 100)); saveProgress.mutate({ lastWatchedSecond: completed ? duration : currentTime, completionPercentage: percentage, status: completed ? 'completed' : 'in_progress' }); }
  function onTimeUpdate() { const seconds = player.current.currentTime; const next = questions.find((q) => !answered.has(String(q.id)) && seconds >= q.timestampSeconds); if (next && !activeQuestion) { player.current.pause(); setActiveQuestion(next); setNotice('Video paused for a quick check.'); return; } if (seconds - lastSavedSecond.current >= 5) { lastSavedSecond.current = seconds; persistProgress(seconds); } }
  function submit(event) { event.preventDefault(); const value = activeQuestion.type === 'multiple' ? [...event.currentTarget.querySelectorAll('input:checked')].map((input) => input.value) : answer; if (!Array.isArray(value) && !value.trim()) return; saveResponse.mutate({ questionId: activeQuestion.id, answer: value }); }
  return <main><Link to="/learn">← Back to my learning</Link><h1>{video.title}</h1><video ref={player} controls src={video.videoUrl} onTimeUpdate={onTimeUpdate} onPause={() => { const current = player.current.currentTime; saveProgress.mutate({ lastWatchedSecond: current, completionPercentage: current / video.durationSeconds * 100, status: 'in_progress' }); }} onEnded={() => saveProgress.mutate({ lastWatchedSecond: video.durationSeconds, completionPercentage: 100, status: 'completed' })} />{activeQuestion && <div className="modal"><form className="card quiz" onSubmit={submit}><h2>Quick check</h2><p>{activeQuestion.prompt}</p>{activeQuestion.type === 'short' ? <textarea value={answer} onChange={(e) => setAnswer(e.target.value)} required /> : activeQuestion.options.map((option) => <label key={option._id}><input type={activeQuestion.type === 'multiple' ? 'checkbox' : 'radio'} name="answer" value={option._id} checked={activeQuestion.type === 'multiple' ? undefined : answer === option._id} onChange={(e) => setAnswer(e.target.value)} /> {option.text}</label>)}<button disabled={saveResponse.isPending}>Submit and continue</button></form></div>}</main>;
}

  */
}

function PlayerExperience({ assignmentId, data }) {
  const player = useRef(null); const client = useQueryClient(); const lastSavedSecond = useRef(0); const [question, setQuestion] = useState(null); const [answer, setAnswer] = useState(''); const [handled, setHandled] = useState(() => new Set((data.progress?.answeredQuestionIds || []).map(String))); const [notice, setNotice] = useState(''); const [playerError, setPlayerError] = useState('');
  const { video, questions, progress } = data; const completed = progress?.status === 'completed' || progress?.completionPercentage >= 100;
  const saveProgress = useMutation({ mutationFn: (payload) => api.patch(`/assignments/${assignmentId}/progress`, payload), onSuccess: () => client.invalidateQueries({ queryKey: ['assignments'] }) });
  const saveAnswer = useMutation({ mutationFn: (payload) => api.post(`/assignments/${assignmentId}/responses`, payload), onSuccess: (_, variables) => { setHandled((current) => new Set([...current, variables.questionId])); setQuestion(null); setAnswer(''); setNotice('Answer saved. Playback resumed.'); player.current?.play().catch(() => setPlayerError('Select play to continue the video.')); } });
  useEffect(() => { if (progress?.lastWatchedSecond && player.current) player.current.currentTime = progress.lastWatchedSecond; }, [progress?.lastWatchedSecond]);
  function persist(currentTime, finished = false) { const duration = player.current?.duration || video.durationSeconds; saveProgress.mutate({ lastWatchedSecond: finished ? duration : currentTime, completionPercentage: finished ? 100 : Math.min(99, Math.round((currentTime / duration) * 100)), status: finished ? 'completed' : 'in_progress' }); }
  function onTimeUpdate() { const currentTime = player.current.currentTime; const next = questions.find((item) => !handled.has(String(item.id)) && currentTime >= item.timestampSeconds); if (next && !question) { player.current.pause(); setQuestion(next); setNotice('Video paused for a quick check.'); return; } if (currentTime - lastSavedSecond.current >= 5) { lastSavedSecond.current = currentTime; persist(currentTime); } }
  function submit(event) { event.preventDefault(); const value = question.type === 'multiple' ? [...event.currentTarget.querySelectorAll('input:checked')].map((input) => input.value) : answer; if (!Array.isArray(value) && !value.trim()) return; if (Array.isArray(value) && !value.length) return; saveAnswer.mutate({ questionId: question.id, answer: value }); }
  return <main><Link to="/learn">Back to my learning</Link><div className="lesson-heading"><div><h1>{video.title}</h1><p>{video.description || 'Complete the video and answer the questions as they appear.'}</p></div>{completed && <span className="completion-badge">Completed - 100%</span>}</div>{notice && <p className="notice" role="status">{notice}</p>}{playerError && <p className="error" role="alert">{playerError}</p>}<video ref={player} controls src={video.videoUrl} onTimeUpdate={onTimeUpdate} onPause={() => { const currentTime = player.current?.currentTime || 0; const duration = player.current?.duration || video.durationSeconds; if (!question && currentTime < duration - 0.25 && !completed) persist(currentTime); }} onEnded={() => { persist(player.current?.duration || video.durationSeconds, true); setNotice('Lesson completed. Great work - this video is now marked 100% complete.'); }} onError={() => setPlayerError('This video could not be played. Ask the admin to use a direct HTTPS MP4 link that allows browser playback.')} />{question && <div className="modal" role="dialog" aria-modal="true" aria-label="Video question"><form className="card quiz" onSubmit={submit}><span className="pill">Video paused at {Math.floor(question.timestampSeconds)} seconds</span><h2>Quick check</h2><p>{question.prompt}</p>{question.type === 'short' ? <textarea value={answer} onChange={(event) => setAnswer(event.target.value)} required aria-label="Your answer" /> : question.options.map((option) => <label key={option._id}><input type={question.type === 'multiple' ? 'checkbox' : 'radio'} name="answer" value={option._id} checked={question.type === 'multiple' ? undefined : answer === option._id} onChange={(event) => setAnswer(event.target.value)} /> {option.text}</label>)}<button disabled={saveAnswer.isPending}>{saveAnswer.isPending ? 'Saving answer...' : 'Submit and continue'}</button>{saveAnswer.error && <p className="error">Your answer could not be saved. Please try again.</p>}</form></div>}</main>;
}
